fix: add missing type annotations
py_jama_client\client.py:251: error: Need type annotation for "data" (hint: "data: list[<type>] = ...")  [var-annotated]
py_jama_client\client.py:251: error: Need type annotation for "linked" (hint: "linked: dict[<type>, <type>] = ...")  [var-annotated]
py_jama_client\apis\test_plans_api.py:69: error: Incompatible types in assignment (expression has type "list[str]", target has type "list[int]")  [assignment]
py_jama_client\apis\activities_api.py:77: error: Dict entry 0 has incompatible type "str": "list[str] | None"; expected "str": "int" [dict-item]
py_jama_client\apis\activities_api.py:79: error: Dict entry 0 has incompatible type "str": "list[str] | None"; expected "str": "int" [dict-item]
py_jama_client\apis\activities_api.py:81: error: Dict entry 0 has incompatible type "str": "list[str]"; expected "str": "int"  [dict-item]