Fix misc bugs and type annotations (#42)
* fix: add missing comma in call to client.put

py_jama_client\apis\baselines_api.py:110: error: Unsupported left operand type for ** ("str")  [operator]

* fix: api classes have no attribute "handle_response_status"

py_jama_client\apis\users_api.py:245: error: "UsersAPI" has no attribute "handle_response_status"  [attr-defined]
py_jama_client\apis\users_api.py:279: error: "UsersAPI" has no attribute "handle_response_status"  [attr-defined]
py_jama_client\apis\items_api.py:288: error: "ItemsAPI" has no attribute "handle_response_status"  [attr-defined]
py_jama_client\apis\items_api.py:762: error: "ItemsAPI" has no attribute "handle_response_status"  [attr-defined]

* fix: set default params when None is passed

py_jama_client\apis\items_api.py:128: error: Unsupported target for indexed assignment ("dict[Any, Any] | None")  [index]

* fix: add missing type annotations

py_jama_client\client.py:251: error: Need type annotation for "data" (hint: "data: list[<type>] = ...")  [var-annotated]
py_jama_client\client.py:251: error: Need type annotation for "linked" (hint: "linked: dict[<type>, <type>] = ...")  [var-annotated]
py_jama_client\apis\test_plans_api.py:69: error: Incompatible types in assignment (expression has type "list[str]", target has type "list[int]")  [assignment]
py_jama_client\apis\activities_api.py:77: error: Dict entry 0 has incompatible type "str": "list[str] | None"; expected "str": "int" [dict-item]
py_jama_client\apis\activities_api.py:79: error: Dict entry 0 has incompatible type "str": "list[str] | None"; expected "str": "int" [dict-item]
py_jama_client\apis\activities_api.py:81: error: Dict entry 0 has incompatible type "str": "list[str]"; expected "str": "int"  [dict-item]